version: 2

# Add necessary apt-get packages
build:
  apt_packages:
    - cmake

# Explicitly set the version of Python and its requirements
# The flat extra_requirements all is equivalent to: pip install .[all]
python:
  version: "3.7"
  install:
    - method: pip
      path: .
      extra_requirements:
        - all

# Build from the docs/ directory with Sphinx
sphinx:
  configuration: docs/source/conf.py
