name: reco_base
channels:
- defaults
- conda-forge
- pytorch
- fastai
dependencies:
- python==3.6.10
- bottleneck==1.2.1
- dask>=0.17.1
- fastparquet>=0.1.6
- ipykernel>=4.6.1
- jupyter>=1.0.0
- matplotlib>=2.2.2
- mock==2.0.0
- numpy>=1.13.3
- pandas>=0.23.4,<1.0.0
- pip>=19.0.3
- pytest>=3.6.4
- pytorch-cpu>=1.0.0
- seaborn>=0.8.1
- scikit-learn>=0.19.1
- scipy>=1.0.0
- scikit-surprise>=1.0.6
- swig==3.0.12
- tensorflow==1.12.0
- lightgbm==2.2.1
- cornac>=1.1.2
- papermill==0.19.1
- tqdm>=4.31.1
- pip:
  - azureml-sdk[notebooks,tensorboard]==1.0.69
  - azure-storage>=0.36.0
  - azure-cli-core>=2.0.75
  - azure-mgmt-cosmosdb>=0.8.0
  - black>=18.6b4
  - category_encoders>=1.3.0
  - dataclasses>=0.6
  - hyperopt==0.1.1
  - idna==2.7
  - locustio==0.11.0
  - memory-profiler>=0.54.0
  - nbconvert==5.5.0
  - pydocumentdb>=2.3.3
  - pymanopt==0.2.3
  - xlearn==0.40a1
  - nni==0.5.2.1.1
