authorName: default
experimentName: surprise_svd
maxExecDuration: 1h
maxTrialNum: 10
searchSpacePath: search_space_svd.json
trainingServicePlatform: local
trial:
  codeDir: .
  command: python3 svd_training.py
  gpuNum: 0
trialConcurrency: 10
tuner:
  builtinTunerName: TPE
  classArgs:
    optimize_mode: maximize
useAnnotation: false
