# ---------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.
# ---------------------------------------------------------

name: azureml-tests
description: "Submit experiment to AzureML cluster"
inputs:
  # azureml experiment name
  EXP_NAME:
    required: true
    type: string
  # type of test - unit or nightly
  TEST_KIND:
    required: true
    type: string
  # test environment - cpu, gpu or spark
  TEST_ENV:
    required: false
    type: string
  # azureml compute credentials
  AZUREML_TEST_CREDENTIALS:
    required: true
    type: string
  # azureml compute subid
  AZUREML_TEST_SUBID:
    required: true
    type: string
  # python version
  PYTHON_VERSION:
    required: true
    type: string
  # test group name
  TEST_GROUP:
    required: true
    type: string

env:
  CPU_CLUSTER_NAME: "cpu-cluster"
  GPU_CLUSTER_NAME: "gpu-cluster"
  RG: "recommenders_project_resources"
  WS: "azureml-test-workspace"
  TEST_LOGS_PATH: '"test_logs.log"'
  PYTEST_EXIT_CODE: "pytest_exit_code.log"

runs:
  using: "composite"
  steps:
    - name: Setup python
      uses: actions/setup-python@v2
      with: 
        python-version: "3.8"
    - name: Install azureml-core and azure-cli on a GitHub hosted server
      shell: bash
      run: pip install azureml-core azure-cli
    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{inputs.AZUREML_TEST_CREDENTIALS}}
    - name: Install wheel package
      shell: bash
      run: pip install wheel
    - name: Create wheel from setup.py
      shell: bash
      run: python setup.py bdist_wheel
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
    - name: Submit CPU tests to AzureML
      shell: bash
      if: contains(inputs.TEST_GROUP, 'cpu')
      run: >-
          python tests/ci/azureml_tests/submit_groupwise_azureml_pytest.py --clustername ${{env.CPU_CLUSTER_NAME}}
          --subid ${{inputs.AZUREML_TEST_SUBID}} --reponame "recommenders" --branch ${{ steps.extract_branch.outputs.branch }}
          --rg ${{env.RG}} --wsname ${{env.WS}} --expname ${{inputs.EXP_NAME}}_${{inputs.TEST_GROUP}}
          --testlogs ${{env.TEST_LOGS_PATH}} --testkind ${{inputs.TEST_KIND}}
          --conda_pkg_python ${{inputs.PYTHON_VERSION}} --testgroup ${{inputs.TEST_GROUP}}
    - name: Submit GPU tests to AzureML
      shell: bash
      if: contains(inputs.TEST_GROUP, 'gpu')
      run: >-
          python tests/ci/azureml_tests/submit_groupwise_azureml_pytest.py --clustername ${{env.GPU_CLUSTER_NAME}}
          --subid ${{inputs.AZUREML_TEST_SUBID}} --reponame "recommenders" --branch ${{ steps.extract_branch.outputs.branch }}
          --rg ${{env.RG}} --wsname ${{env.WS}} --expname ${{inputs.EXP_NAME}}_${{inputs.TEST_GROUP}}
          --testlogs ${{env.TEST_LOGS_PATH}} --add_gpu_dependencies --testkind ${{inputs.TEST_KIND}}
          --conda_pkg_python ${{inputs.PYTHON_VERSION}} --testgroup ${{inputs.TEST_GROUP}}
    - name: Submit PySpark tests to AzureML
      shell: bash
      if: contains(inputs.TEST_GROUP, 'spark')
      run: >-
          python tests/ci/azureml_tests/submit_groupwise_azureml_pytest.py --clustername ${{env.CPU_CLUSTER_NAME}}
          --subid ${{inputs.AZUREML_TEST_SUBID}} --reponame "recommenders" --branch ${{ steps.extract_branch.outputs.branch }}
          --rg ${{env.RG}} --wsname ${{env.WS}} --expname ${{inputs.EXP_NAME}}_${{inputs.TEST_GROUP}}
          --testlogs ${{env.TEST_LOGS_PATH}} --add_spark_dependencies --testkind ${{inputs.TEST_KIND}}
          --conda_pkg_python ${{inputs.PYTHON_VERSION}} --testgroup ${{inputs.TEST_GROUP}}}
    - name: Print test logs
      shell: bash
      run: cat ${{env.TEST_LOGS_PATH}}
    - name: Get exit status
      shell: bash
      id: exit_status
      run: echo ::set-output name=code::$(cat ${{env.PYTEST_EXIT_CODE}})

