name: get-test-groups
description: "Get test group names from tests_groups.py"
inputs:
  # type of test - unit or nightly
  TEST_KIND:
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Get test group names
      id: get_test_groups
      run: |
        if [[ ${{ inputs.TEST_KIND }} == "nightly" ]]; then
          test_groups_str=$(python -c 'from tests.ci.azureml_tests.test_groups import nightly_test_groups; print([t for t in nightly_test_groups.keys() if "${{inputs.TEST_ENV}}" in t])')
        else
          test_groups_str=$(python -c 'from tests.ci.azureml_tests.test_groups import unit_test_groups; print(list(unit_test_groups.keys()))')
        fi
        echo ::set-output name=test_groups::$test_groups_str
  outputs:
    test_groups: ${{steps.get_test_groups.outputs.test_groups}}