# ---------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.
# ---------------------------------------------------------

# ToDo: workflow that gets triggered on a PR to main/staging
# and submits an experiment to run tests on AML cluster
name: trigger-aml-tests

on:
  # pull_request:
  #   branches: [ staging, main ]

  # enable manual trigger
  workflow_dispatch:
    input:
      tags:
        description: 'Tags to label this manual run (optional)'
        default: 'Anything to describe this manual run'

jobs:
  Trigger-tests-on-AML-with-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      # - name: Check out repository code
      #   uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with: 
          python-version: "3.8"
      - name: Install azureml-core and azure-cli on a GitHub hosted server
        run: pip install azureml-core azure-cli
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZ_AE_CREDS}}
      # - name: Submit a test to AML
      #   run: python tests/ci/aml_tests_new/submit_azureml_pytest.py
      - run: echo "🍏 This job's status is ${{ job.status }}."