# ---------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.
# ---------------------------------------------------------

name: azureml-unit-tests

on:
  # pull_request_target allows execution of workflows in the context
  # of a base repository. When a PR is raised from a forked repo, it
  # gives the workflow access to AZUREML_TEST_CREDENTIALS, stored as
  # a repo level secret, which is needed to trigger execution of unit
  # tests on AzureML compute.
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - 'staging'
      - 'main'

  # enable manual trigger
  workflow_dispatch:
    input:
      tags:
        description: 'Tags to label this manual run (optional)'
        default: 'Anything to describe this manual run'

  # make this workflow reusable
  workflow_call:

jobs:

  check-changes:
    # Check if there are changes in the unit tests related code which
    # includes:
    #   * examples/
    #   * recommenders/
    #   * tests/
    #   * setup.py
    runs-on: ubuntu-latest
    outputs:
      code: ${{ steps.filter.outputs.code }}
    steps:
      - uses: actions/checkout@v3

      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            code:
              - examples/**
              - recommenders/**
              - tests/**
              - setup.py

  unit-tests:
    needs: check-changes
    # Unit tests will be run only when related code changes
    if: needs.check-changes.outputs.code == 'true'
    uses: ./.github/workflows/azureml-template.yml
    with:
      EXP_NAME: 'unit_tests'
      TEST_KIND: 'unit'
    secrets: inherit
