# ---------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.
# ---------------------------------------------------------

name: azureml-cpu-nightly

on:
  #          ┌───────────── minute (0 - 59)
  #          │ ┌───────────── hour (0 - 23)
  #          │ │  ┌───────────── day of the month (1 - 31)
  #          │ │  │  ┌───────────── month (1 - 12 or JAN-DEC)
  #          │ │  │  │ ┌───────────── day of the week (0 - 6 or SUN-SAT)                                  
  #          │ │  │  │ │
  #          │ │  │  │ │
  schedule: 
    - cron: '0 0 */2 * *'  # basically running every other day at 12AM
    # cron works with default branch (main) only: # https://github.community/t/on-schedule-per-branch/17525/2
  
  push:
    # because we can't schedule runs for non-main branches,
    # to ensure we are running the build on the staging branch, we can add push policy for it
    branches: [staging]

  # pull_request_target allows execution of workflows in the context
  # of a base repository. When a PR is raised from a forked repo, it
  # gives the workflow access to AZUREML_TEST_CREDENTIALS, stored as
  # a repo level secret, which is needed to trigger execution of unit
  # tests on AzureML compute.
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - 'main'
    paths:
      # Unit tests will be run only when there are changes in the
      # unit tests related code including:
      - examples/**
      - recommenders/**
      - tests/**
      - setup.py

  # enable manual trigger
  workflow_dispatch:
    input:
      tags:
        description: 'Tags to label this manual run (optional)'
        default: 'Anything to describe this manual run'

  # make this workflow reusable
  workflow_call:

jobs:
  get-test-groups:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Get test group names
        id: get_test_groups
        uses: ./.github/actions/get-test-groups
        with:
          TEST_KIND: "nightly"
          TEST_ENV: "cpu"
      - name: Print test group names
        run: echo ${{ steps.get_test_groups.outputs.test_groups }}
        shell: bash
    outputs:
      test_groups: ${{ steps.get_test_groups.outputs.test_groups }}

  execute-tests:
    needs: get-test-groups
    name: ${{ join(matrix.*, ', ') }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['"python=3.7"', '"python=3.8"', '"python=3.9"']
        test-group:  ${{ fromJSON(needs.get-test-groups.outputs.test_groups) }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Execute tests
        uses: ./.github/actions/azureml-test
        id: execute_tests
        with:
          EXP_NAME: 'nightly_tests'
          TEST_KIND: 'nightly'
          TEST_ENV: 'cpu'
          AZUREML_TEST_CREDENTIALS: ${{ secrets.AZUREML_TEST_CREDENTIALS }}
          AZUREML_TEST_SUBID: ${{ secrets.AZUREML_TEST_SUBID }}
          PYTHON_VERSION: ${{ matrix.python-version }}
          TEST_GROUP: ${{ matrix.test-group }}
