name: pr-gate

on:
  push:
    branches: [ laserprec/ghaction-sandbox, laserprec/ghaction-ci ]

jobs:
  run-unit-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python: [3.6]
        # different kind of tests are located in tests/<unit|integration|smoke> folders
        test-kind: ['unit'] 
        # pytest markers configured in tox.ini. See https://docs.pytest.org/en/6.2.x/example/markers.html
        test-marker: ["not gpu and not spark and not notebooks", "notebooks and not gpu and not spark"]

    steps:
    - uses: actions/checkout@v2
    - name: Use Python ${{ matrix.python }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    
    - name: Install build dependencies (tox)
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install tox
    
    - name: Run ${{ matrix.test-kind }} tests ('${{ matrix.test-marker }}'-${{ matrix.python }}-${{ matrix.os }})
      # '-e py' will use the default 'python' executable found in system path
      # for why using tox, see: https://tox.readthedocs.io/en/latest/index.html
      # tox will do:
      #   1. build and install source distribution (sdist)
      #   2. run static analysis on the code (not implemented yet)
      #   3. run all of the specified test environment (i.e. run tests in different pyversions, etc)
      #   4. show test reports
      run: |
        tox -e py -- tests/${{ matrix.test-kind }} -m '${{ matrix.test-marker }}'
